### PR TITLE
docs: Adhere to REUSE specification

### PR DESCRIPTION
**Pull request by tboehler1**
This is the first repository that is REUSEified and serves as an example.

Link to specification: https://reuse.software/spec/

### CODE REVIEW

**Review by iluminat23 — CHANGES_REQUESTED** [review]
The your must be a range 2021-2023, as far as I understand copyright

**Review by iluminat23 — DISMISSED** [review]

**Comment by iluminat23** [comment]
The example here: https://reuse.software/spec/#comment-headers has a line with and a line without. So I guess it ist optional. So I would prefer to leaving it out. As it is our global support address and has no additional value. In case of legal action the support address is not the right address anyways.

**Comment by tboehler1** [comment]
> Is that a standard with the email information, because we don't do it in the debian/changelog (yet)?

This is by far the most common way to denote `SPDX-FileCopyrightText` from *my* experience. You can put something else there, though, as indicated by the SPDX spec: https://spdx.github.io/spdx-spec/v2.3/file-tags/

**Comment by tboehler1** [comment]
> In case of legal action the support address is not the right address anyways.

Can/Should we put a different address here?

**Comment by iluminat23** [comment]
No, I would just leave it out. KUNBUS GmbH is the legal entity. We don't have any dedicated address except our support address. And the support address is not the correct place to file any legal complaints.

**Review by iluminat23 — APPROVED** [review]

**Pull request merged**
